common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * @property string $image
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $company
 * @property string $position
 * @property string $auth_key
 * @property string $ip_address
 * @property integer $country_id
 * @property integer $type_id
 * @property integer $language_id
 * @property integer $login_count
 * @property integer $social
 * @property integer $status
 * @property string $role
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property UserVehicle[] $vehicles rider cars
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    const TYPE_RIDER = 1;
    const TYPE_DRIVER = 2;

    const SCENARIO_MANUAL = 'manual';
    const SCENARIO_SOCIAL = 'social';

    const SIGNUP_MANUAL = 1;
    const SIGNUP_FB = 2;
    const SIGNUP_GP = 3;

    const ROLE_ADMIN = 'admin';
    const ROLE_MODERATOR = 'moderator';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login_count', 'type_id', 'social', 'country_id', 'language_id'], 'integer'],
            [['created_at', 'updated_at'], 'integer'],
            [['ip_address'], 'ip'],

            [['phone'], 'string'],
            [['address'], 'string', 'max' => 255],

            [['first_name', 'last_name', 'email'], 'trim'],
            [['first_name', 'last_name', 'email', 'phone'], 'required'],

            [['username'], 'string','max' => 64],

            [['role'], 'string','max' => 32],

            [['first_name', 'last_name', 'phone', 'image'], 'string', 'min' => 3, 'max' => 32],

            [['email'], 'string', 'max' => 255],
            ['status', 'default', 'value' => self::STATUS_DELETED],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],

            ['email', 'unique', 'targetClass' => '\common\models\User',
                'message' => Yii::t('main','This email address has already been taken.')
            ],

            [
                ['first_name', 'last_name', 'email', 'phone'],
                'filter',
                'filter' => function ($value) {
                    return filter_var($value, FILTER_SANITIZE_STRING);
                }
            ],
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();

        $scenarios[self::SCENARIO_MANUAL] = ['first_name', 'last_name', 'email', 'username', 'login_count', 'social', 'language_id', 'status', 'country_id', 'created_at', 'updated_at', 'ip_address', 'phone', 'type_id', 'address', 'image'];
        $scenarios[self::SCENARIO_SOCIAL] = ['first_name', 'last_name', 'email', 'username', 'login_count', 'social', 'language_id', 'status', 'country_id', 'created_at', 'updated_at', 'ip_address'];

        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'first_name' => Yii::t('main', 'First name'),
            'last_name' => Yii::t('main', 'Last name'),
            'language_id' => Yii::t('main', 'Language'),
            'country_id' => Yii::t('main', 'Country'),
            'address' => Yii::t('main', 'Address'),
            'type_id' => Yii::t('main', 'Type'),
            'social' => Yii::t('main', 'Signup method'),
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function setIpAddress()
    {
        $this->ip_address = Yii::$app->request->getUserIP();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicles()
    {
        return $this->hasMany(UserVehicle::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(Country::className(), ['id' => 'country_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguage()
    {
        return $this->hasOne(Language::className(), ['id' => 'language_id']);
    }

    public function getLoggedInData()
    {
        $userArr = [
            'id' => $this->id,
            'first_name' => $this->first_name,
            'last_name' => $this->last_name,
            'username' => $this->username,
            'email' => $this->email,
            'phone' => $this->phone,
            'status' => $this->status,
            'type_id' => $this->type_id,
            'token' => $this->auth_key,
            'completed' => ($this->type_id == self::TYPE_DRIVER) ? 1 : ((int)(count($this->vehicles) > 0))
        ];

        return $userArr;
    }

    public function getProfileImg()
    {
        return $this->image ? Yii::getAlias('@profile/') . $this->image : '/images/profilephoto.png';
    }

    public function assignRole($oldRole)
    {
        if (Yii::$app->user->can('admin') && UserUtils::getRoleByName($this->role)) {
            $auth = \Yii::$app->authManager;
            $authorRole = $auth->getRole($this->role);
            $authorOldRole = $auth->getRole($oldRole);

            //remove old role
            if ($oldRole) {
                Yii::$app->authManager->revoke( $authorOldRole, $this->id );
            }

            //assign new role
            $auth->assign($authorRole, $this->id);
        }
    }
}

backend/views/media/_form.php
<?php

use dosamigos\ckeditor\CKEditor;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Media */
/* @var $form yii\widgets\ActiveForm */
$this->registerJs("CKEDITOR.plugins.addExternal('justify', '/js/ckeditor/justify/plugin.js', '');");
$this->registerJs("CKEDITOR.plugins.addExternal('confighelper', '/js/ckeditor/confighelper/plugin.js', '');");
?>

<div class="media-form">
    <ul class="nav nav-tabs">
        <?php foreach ($_SESSION['languages'] as $lang):?>
            <li class="<?= Yii::$app->language == $lang ? 'active':''?>"><a class="text-uppercase" data-toggle="tab" href="#section_<?=$lang?>"><?=$lang?></a></li>
        <?php endforeach;?>
    </ul>
    <?php $form = ActiveForm::begin(['id' => 'media-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="tab-content">
        <?php foreach ($_SESSION['languages'] as $lang):?>
            <div id="section_<?=$lang?>" class="tab-pane fade<?= Yii::$app->language == $lang ? ' in active':''?>">
                <?= $form->field($model, 'title'.(Yii::$app->language == $lang?'':'_'.$lang))->textInput(['maxlength' => true,'data-slugify'=>"#media-slug".(Yii::$app->language == $lang?'':'_'.$lang)]) ?>
                <?= $form->field($model, 'slug'.(Yii::$app->language == $lang?'':'_'.$lang))->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'short_desc'.(Yii::$app->language == $lang?'':'_'.$lang))->widget(CKEditor::className(), [
                    'options' => ['rows' => 4],
                    'preset' => 'full',
                    'clientOptions' => [
                        'extraPlugins' => 'justify,confighelper',
                        'height' => '150px',
                        'allowedContent' => false,
                        'filebrowserUploadUrl' => '/admin/site/upload-image',
                        'placeholder' => 'Short description...'
                    ]
                ])->label(false) ?>

                <?= $form->field($model, 'description'.(Yii::$app->language == $lang?'':'_'.$lang))->widget(CKEditor::className(), [
                    'options' => ['rows' => 4],
                    'preset' => 'full',
                    'clientOptions' => [
                        'extraPlugins' => 'justify,confighelper',
                        'height' => '300px',
                        'allowedContent' => false,
                        'filebrowserUploadUrl' => '/admin/site/upload-image',
                        'placeholder' => 'Description...'
                    ]
                ])->label(false) ?>
            </div>

        <?php endforeach;?>
    </div>
    <?= FileInput::widget([
        'name' => 'Media[image]',
        'pluginOptions' => [
            'initialPreview' => $model->image ? Yii::getAlias('@media/').$model->image : false,
            'initialPreviewAsData' => !empty($model->image),
            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  $model->isNewRecord ? 'Select image' : 'Change media image'
        ],
        'options' => ['accept' => 'image/*']
    ]);?>

    <?= $form->field($model, 'page_id')->dropDownList($pages, ['prompt' => 'Select page']) ?>


    <?= $form->field($model, 'enabled')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('main', 'Create') : Yii::t('main', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/media/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\MediaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="media-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'image') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?= $form->field($model, 'view_count') ?>

    <?php // echo $form->field($model, 'enabled') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('main', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('main', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/media/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Media */

$this->title = Yii::t('main', 'Create Media');
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Media'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-create">

    <div class="card">
        <div class="header">
            <h4 class="title"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="content">

    <?= $this->render('_form', [
        'model' => $model,
        'pages' => $pages
    ]) ?>
        </div>
    </div>

</div>

backend/views/media/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\MediaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('main', 'Media');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-index">
    <div class="card">
        <div class="header">
            <h4 class="title"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="content">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('main', 'Create Media'), ['create'], ['class' => 'btn btn-primary']) ?>
    </p>
<?php Pjax::begin(); ?>
<?php
    $this->registerJs(' 
       $("input[name*=\'created_at\']").datepicker({
            format: \'yyyy-mm-dd\',
            autoclose: true
        });
        $("input[name*=\'[updated_at]\']").datepicker({
            format: \'yyyy-mm-dd\',
            autoclose: true

        });'); ?>
            <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            [
                'attribute' => 'created_at',
                'value' => function($data) {
                    return date('Y-m-d H:i:s', $data->created_at);
                },

            ],
            [
                'attribute' => 'updated_at',
                'value' => function($data) {
                    return date('Y-m-d H:i:s', $data->updated_at);
                }
            ],
            'view_count',
            // 'enabled',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>
    </div>
</div>

backend/views/media/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Media */

$this->title = Yii::t('main', 'Update {modelClass}: ', [
    'modelClass' => 'Media',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Media'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('main', 'Update');
?>
<div class="media-update">
    <div class="card">
        <div class="header">
            <h4 class="title"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="content">

    <?= $this->render('_form', [
        'model' => $model,
        'pages' => $pages
    ]) ?>
        </div>
    </div>
</div>

backend/views/media/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Media */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Media'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-view">
    <div class="card">
        <div class="header">
            <h4 class="title"><?= Html::encode($this->title) ?></h4>
        </div>
        <div class="content">

    <p>
        <?= Html::a(Yii::t('main', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('main', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('main', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                    'attribute' => 'image',
                    'value' => (Yii::getAlias('@mediaThumb/') . $model->image),
                    'format' => ['image',['width'=>'100','height'=>'100']],
            ],
            [
                'attribute' => 'created_at',
                'value' => function($data) {
                    return date('Y-m-d H:i:s', $data->created_at);
                },

            ],
            [
                'attribute' => 'updated_at',
                'value' => function($data) {
                    return date('Y-m-d H:i:s', $data->updated_at);
                }
            ],
            'view_count',
            'enabled',
        ],
    ]) ?>
        </div>
    </div>
</div>